function dop = dopStepSettings(h,steps)
% DOPOSCCI3: dopStepSettings
%
% notes:
% DOPOSCCI step settings/information for each step
%
% Use:
%
% dop.steps = dopStepSettings;
%
% where:
% > Inputs:
% - dop = dop matlab structure
%
% > Outputs: (note, varargout - therefore optional or as many as you want)
% - dop = dop matlab sructure
%
%
% Created: 14-Oct-2015 NAB
% Edits:
% 15-Oct-2015 NAB plugging away
% 28-Oct-2015 NAB fixed progression button function
% 02-Dec-2015 NAB adjusting for optional buttons
% 03-Aug-2016 NAB lots of development in the lead up to the Laterality
%   workshop - more or less finished :)
% 30-Aug-2016 NAB corrected for extra buttons in step movement

try
    fprintf('\nRunning %s:\n',mfilename);
    
    % an order will need to be generated but I'm thinking of having a
    % switch for different steps to a structure variable with a generic set
    % of options to drive the different components required for each step
    
    
    %% get dop structure
    dop = get(h,'UserData');
    
    %% define list of steps
    dop.step.steps = {'welcome'};
    dop.step.steps(end+1:end+numel(dop.step.action.string)) = lower(dop.step.action.string);%...;%...
    if sum(ismember(dop.step.action.tag,'save'))
    dop.tmp.last_action_num = diff([find(ismember(dop.step.action.string,'Save')),numel(dop.step.action.string)])-1;
    else
        dop.tmp.last_action_num = diff([find(ismember(dop.step.action.string,'LI')),numel(dop.step.action.string)])-1;
    end
    
    dop.step.steps(end-dop.tmp.last_action_num:end+1) = {'finished',dop.step.steps{end-dop.tmp.last_action_num:end}};
    dop = rmfield(dop,'tmp');
    %         {'welcome','data_file','channels','event',...
    %         'timing'}; %,'downsample','definition','task_name'
    %     dop.step.action.string = {'Import','Channels','Events','Norm',...
    %         'Heart','Epoch','Screen','Baseline','LI'}; % ,'Plot'
    dop.step.steps_optional =[];
    if dop.step.option.on
        dop.step.steps_optional = lower(dop.step.option.string);%...
    end
    %         {'downsample','trim'};
    dop.step.optional = 0;
    if exist('steps','var') && ~isempty(steps) && isnumeric(steps) && steps
        % just make sure we have the steps variable to work with
        set(h,'UserData',dop);
        return
    elseif exist('steps','var') && ~isempty(steps) && ~isnumeric(steps)
        switch steps
            case 'start'
                dop.step.next.n = 1;
                dop.step.current.n = 0;
            case dop.step.steps_optional
                fprintf('Optional step: ''%s''\n',steps);
                dop.step.optional = 1;
                dop.step.next.name = steps;
            otherwise
                dop.tmp.warn = sprintf('''%s'' step not recognised. Aborting',steps);
                fprintf('%s\n',dop.tmp.warn);
                warndlg(dop.tmp.warn,'Unknown step')
                return
        end
    end
    
    %% settings details
    if dop.step.optional || dop.step.next.n ~= dop.step.current.n || dop.step.next.n == 1
        % default settings
        dop.step.next.name = dop.step.steps{dop.step.next.n};
        dop.step.next.left_pos = .15;
        dop.step.next.title_position = [dop.step.next.left_pos .87 .7 .1];
        dop.step.next.info_position = [dop.step.next.left_pos .7 .7 .2];
        dop.step.next.HorizontalAlignment = {'left','left'};
        switch dop.step.next.name
            %% > welcome:
            case 'welcome'
                %% - information text field
                dop.step.next.style = {'text','text','text','text'};
                dop.step.next.string = {'Welcome to ''dopStep'' - an introduction to DOPOSCCI.',...
                    ['This is a step through guide for summarising ',...
                    'functional Transcranial Doppler Ultrasound (fTCD) data. ',...
                    'The name ''DOPOSCCI'' is a combinationed of ''Doppler'' ',...
                    'and ''OSCCI'' (Oxford Study of Chidlren''s ',...
                    'Communication Impairments) - the research lab where ',...
                    'the toolbox was developed.']...
                    ['Firstly, make sure you can read this text (increase ',...
                    'font size with the ''+'' button below). Then have a ',...
                    'look at the different buttons. At the top you can move ',...
                    'forwards and backwards through the processing steps. These ',...
                    'steps relate to the ''Action'' buttons at the bottom and will become ',...
                    'clickable when relevant.'],...
                    ['To get started ',...
                    'click on the ''next'' button in the top right corner.']...
                    };
                dop.step.next.tag = {'title','info','overview','started'};
                dop.step.next.position = [dop.step.next.title_position;...
                    dop.step.next.info_position; ...
                    [dop.step.next.left_pos .5 .7 .2];....
                    [dop.step.next.left_pos .3 .7 .2];...
                    [dop.step.next.left_pos .1 .7 .2];
                    ];
                dop.step.next.HorizontalAlignment = [...
                    dop.step.next.HorizontalAlignment,{'left','left','left'}];
                case 'finished'
                %% - information text field
                dop.step.next.style = {'text','text','text','text','text'};
                dop.step.next.string = {'That''s all there is for ''dopStep'' - an introduction to DOPOSCCI.',...
                    ['You can always come back to this intro to look at ',...
                    'data quickly but the next step is to look at ',...
                    'the ''dop'' variable but pressing the ''dop'' button ',...
                    'and/or ',...
                    'some of the code created or the ''dopOSCCIexample.m'' ',...
                    'file (type: ''edit dopOSCCIexample'' in the ',...
                    'MATLAB command window. Using this, you''ll be able ',...
                    'to develop your own scripts and speed up the ',...
                    'processing of your data.'],...
                    ['If this software is been useful to you, please reference ',...
                    'the following papers:'],...
                    ['Badcock, N. A., Holt, G., Holden, A., & Bishop, ',...
                    'D. V. M. (2012). dopOSCCI: A functional transcranial ',...
                    'Doppler ultrasonography summary suite for the ',...
                    'assessment of cerebral lateralization of cognitive ',...
                    'function. Journal of Neuroscience Methods, 204(2), ',...
                    '383-388. http://doi.org/10.1016/j.jneumeth.2011.11.018'],...
                    ['Badcock NA, Spooner R, Hofmann J, Flitton AJ, ',...
                    'Elliott S, Kurylowicz L, Lavrencic LM, Payne HM, ',...
                    'Holt GK, Holden A, Churches OF, Kohler MJ, Keage HA. ',...
                    '(2016) What Box: a task for assessing language ',...
                    'lateralisation in young children. PeerJ Preprints ',...
                    '4:e1939v2 https://doi.org/10.7287/peerj.preprints.1939v2']};
                dop.step.next.tag = {'title','info','doposcci_info','cite_text',...
                    'cite1','cite2'};
                dop.step.next.position = [dop.step.next.title_position;...
                    dop.step.next.info_position; ...
                    [dop.step.next.left_pos .65 .7 .05];...
                     [dop.step.next.left_pos .4 .7 .2];...
                      [dop.step.next.left_pos .2 .7 .2];...
                       [dop.step.next.left_pos .05 .7 .15];...
                    ];
                dop.step.next.HorizontalAlignment = [...
                    dop.step.next.HorizontalAlignment,...
                    {'left','left','left'}];
                %% >> import:
            case 'import'
                dop.step.next.style = {'text','text','edit','edit','pushbutton',...
                    'text','text'};
                dop.step.next.string = {'Import data:',...
                    ['We''ll start by importing an fTCD file. Use the ',...
                    'options below to type the full path of the file (i.e., folder ',...
                    'and file name) or use ',...
                    'pushbutton to browse for the file.'],...
                    'Data file:','empty','Browse',...
                    ['Now that you''ve got a file, try importing it ',...
                    'by clicking the ''Import'' button'],...
                    ['If the data imported okay, you should be able ',...
                    'to have a look at it with the ''Plot'' button. ',...
                    'Bear in mind that you will need to adjust the ',...
                    'y-axis to about 200 to see the data. Adjusting ',...
                    'x-axis to 10 seconds will allow you to see the ',...
                    'heart beats.']};
                if isfield(dop,'file') && exist(dop.file,'file')
                    dop.step.next.string{3} = dop.file;
                end
                dop.step.next.tag = {'title','info','data_file_text','data_file','data_file_browse',...
                    'import_text','plot_text'};
                dop.step.next.position = [dop.step.next.title_position;...
                    dop.step.next.info_position;
                    dop.step.next.left_pos .65 .1 .1; ...
                    dop.step.next.left_pos+.1 .65 .5 .1;...
                    dop.step.next.left_pos+.1+.5 .65 .1 .1;
                    dop.step.next.left_pos .5 .6 .1;...
                    dop.step.next.left_pos .25 .65 .2];
                dop.step.next.HorizontalAlignment = [dop.step.next.HorizontalAlignment,...
                    {'center','center','center','left','left'}];
                dop.step.next.Enable = {[],[],'off','on','on',[],[]};
                dop.step.next.Callback = {[],[],[],[],'dopStepBrowseFile',[],[]};
                dop.step.next.Visible = {'on','on','on','on','on','off','off'};
            case 'channels'
                
                dop.step.next.style = {'text','text','edit','popup',...
                    'edit','popup','edit','popup','text'};
                % create channel lists for dropdown/popup menu
                dop.step.next.ch_list = [];
                if isfield(dop,'data') && isfield(dop.data,'use')
                    for k = 1 :  size(dop.data.use,2)
                        dop.step.next.ch_list{k} = sprintf('column_%u',k);
                        if isfield(dop.data,'file_info') && isfield(dop.data.file_info,'dataLabels') ...
                                && numel(dop.data.file_info.dataLabels) >= k
                            if size(dop.data.use,2) < numel(dop.data.file_info.dataLabels)
                                dop.step.next.ch_list{k} = dop.data.channel_labels{k};
                            else
                                dop.step.next.ch_list{k} = dop.data.file_info.dataLabels{k};
                            end
                        end
                    end
                else
                    dop.step.next.ch_list = {'empty'};
                end
                dop.step.next.string = {'Data channels:',...
                    ['For fTCD data, we need to know which data column ',...
                    'should be treated as the left, right, and event ',...
                    'channels. Please select these from the available ',...
                    'columns. Then click the ''Channels'' button to extract ',...
                    'these from the rest of the data.'],...
                    'Left:',dop.step.next.ch_list,'Right:',dop.step.next.ch_list,...
                    'Event:',dop.step.next.ch_list,...
                    ['If the data channels were extracted correctly, ',...
                    'you should be able to have a look at them with ',...
                    'the ''Plot'' button.']};
                %                 if isfield(dop,'file') && exist(dop.file,'file')
                %                     dop.step.next.string{3} = dop.file;
                %                 end
                dop.step.next.tag = {'title','info','left_text','left_channel',...
                    'right_text','right_channel',...
                    'event_text','event_channel','ch_plot_text'};
                dop.step.next.position = [dop.step.next.title_position;...
                    dop.step.next.info_position; ...
                    .2 .7 .1 .05; .3 .65 .3 .1; ...
                    .2 .55 .1 .05; .3 .5 .3 .1; ...
                    .2 .4 .1 .05; .3 .35 .3 .1;
                    .1 .25 .8 .1];
                dop.step.next.HorizontalAlignment = [dop.step.next.HorizontalAlignment,...
                    {'center','center','center','center','center','center','left'}];
                dop.step.next.Enable = {[],[],'off','on','off','on','off','on','off'};
                dop.step.next.Visible = {'on','on','on','on','on','on','on','on','off'};
                dop.step.next.Callback = {[],[],[],'dopStepGetChannel',...
                    [],'dopStepGetChannel',[],'dopStepGetChannel',[]};
                %% downsample
            case 'downsample'
                dop.step.next.style = {'text','text','text','edit','edit'};
                dop.step.next.string = {'Downsample data:',...
                    'This is an optional step - feel free to skip.',...
                    ['Functional Transcranial Doppler Ultrasound (fTCD) data is ',...
                    'often recorded at 100 Hertz (100 samples be second) = ',...
                    'one piece of information every 10 milliseconds. ',...
                    'Traditionally, fTCD data has been downsampled - ',...
                    ' every 4th data point retained and the rest excluded. ',...
                    ' There are 2 reasons for this. 1) Historically ',...
                    'computers didn''t have the processing ',...
                    'power to deal with this much data - not now a ',...
                    'limitation. 2) 10 millisecond accuracy is unnecessary ',...
                    'when analysing signals that occur over multiple seconds.'],...
                    'Downsample','type number'};
                dop.step.next.tag = {'title','info','downsample_hist','downsample_text','downsample_rate'};
                dop.step.next.position = [dop.step.next.title_position;...
                    dop.step.next.info_position;
                    .1 .55 .8 .3;...
                    .3 .4 .2 .1; .5 .4 .2 .1];
                dop.step.next.HorizontalAlignment = [dop.step.next.HorizontalAlignment,{'left','center','center'}];
                dop.step.next.Enable = {[],[],[],'off','on'};
                dop.step.next.Callback = {[],[],[],[],'dopStepGetDef'};
            case 'events'
                dop.step.next.style = {'text','text','edit','edit','text','edit','edit','text'};
                dop.step.next.string = {'Event markers:',...
                    ['To determine the timing of the event markers, ',...
                    'we need to separate the event markers from noise. ',...
                    'To do this, the function will assume that data in ',...
                    'the event channel above a certain height ',...
                    '(e.g., 1000) is an event. If you''re unsure, ',...
                    'have a look at the y-value ',...
                    'of your event markers in the plot.'],...
                    'Event Height:','type a number',...
                    ['You can also enter the expected separation (in seconds) ',...
                    'between event markers. If you do, the function will ',...
                    'indicate whether you have any outliers which might be ',...
                    'cause for you to manually exclude them (see dopEpochScreenManual.m).'],...
                    'Event Separation:','type a number',...
                    ['If you have a look at the ''Plot'' now, you should see that ',...
                    'there are only 3 data channels available.']};
                dop.step.next.tag = {'title','info','event_height_text','event_height',...
                    'event_sep_info','event_sep_text','event_sep','event_chan_plot_info'};
                dop.step.next.position = [dop.step.next.title_position;...
                    dop.step.next.info_position;
                    dop.step.next.left_pos .6 .2 .1; dop.step.next.left_pos+.2 .6 .2 .1;... 'event_height_text','event_height'
                    dop.step.next.left_pos .4 .7 .15;...  'event_sep_info'
                    dop.step.next.left_pos .275 .2 .1; dop.step.next.left_pos+.2 .275 .2 .1;... %'event_sep_text','event_sep'
                    dop.step.next.left_pos .15 .7 .075];% 'event_chan_plot_info'];
                dop.step.next.HorizontalAlignment = [dop.step.next.HorizontalAlignment,...
                    {'center','center','left','center','center','left'}];
                dop.step.next.Enable = {[],[],'off','on','on','off','on','off'};
                dop.step.next.Callback = {[],[],[],'dopStepGetDef',[],[],'dopStepGetDef',[]};
                
                %% > heart cycle integration
            case 'heart'
                dop.step.next.style = {'text','text',...
                    'text','text','text','checkbox','text','text','radio'};
                dop.step.next.string = {'Heart Cycle Integration:',...
                    ['Michael Deppe tested many different methods for ',...
                    'cleaning up the blood flow velocity signal and ',...
                    'found that removing the ''heart cycle'' (ie ',...
                    'heart beat patterns) using a ''step function'' was ',...
                    'best.'],...
                    'The step function:',...
                    ['The step function simply involves finding the peaks ',...
                    'of the heart beats and taking the average between ',...
                    'these points. Due to changes in velocity ',...
                    'over time, the result looks like a staircase going ',...
                    'up or down.'],...
                    ['You can explore what this looks like by viewing the ',...
                    'plot within this step. Check the box below to do this.'],...
                    'View heart cycle correction',...
                    ['There''s a choice about whether you use the step ',...
                    'function (ie flat line between points) or a linear ',...
                    'function (ie diagonal line between points).'],...
                    'Function type:',{'step','linear'}};
                dop.step.next.tag = {'title','info','title2','info2','info3',...
                    'hc_plot','type_info','type_title','hc_type'};
                
                dop.step.next.position = [dop.step.next.title_position;... [dop.step.next.left_pos .87 .7 .1];
                    dop.step.next.info_position;... [dop.step.next.left_pos .7 .7 .1];
                    dop.step.next.left_pos .7 .7 .05; ... % title2
                    dop.step.next.left_pos .55 .7 .15; ... % info 2
                    dop.step.next.left_pos .5 .7 .05; ... % info 3
                    dop.step.next.left_pos .45 .5 .05; ... % plot_check
                    dop.step.next.left_pos .275 .7 .075; ... % type_text
                    dop.step.next.left_pos .175 .15 .075; ... % type_text
                    dop.step.next.left_pos+.15 .175 .2 .075; ... % hc_type_radio
                    ]; %title2
                dop.step.next.HorizontalAlignment = [dop.step.next.HorizontalAlignment,...
                    {'left','left','left','left','left','left','left'}];
                dop.step.next.Enable = {[],[],[],[],[],'on',[],[],'on'};
                
                dop.step.next.visible = {'on','on',...
                    'on','on','on','on','on','on','on'};
                dop.step.next.Callback = {[],[],[],[],[],'dopStepGetDef',...
                    [],[],'dopStepGetDef'};
            case 'norm'
                dop.step.next.style = {'text','text','edit','radio',...
                    'text','edit','edit','edit',...
                    'text','edit','edit','edit'};
                dop.step.next.string = {'Data Normalisation:',...
                    ['When measuring blood flow velocity bilaterally ',...
                    '(i.e., on the left and right sides of the head), ',...
                    'it is likely that the insonation angle for each probe ',...
                    'will be different, resulting in differing overall ',...
                    'activation levels between sides. In order to correct ',...
                    'for this, we set the average of the two channels to the ',...
                    'same value. There are three ways to do this with ',...
                    'specific requirements. ''Overall'' is the most ',...
                    'straight forward - adjusting values across the ',...
                    'whole of the data recording. The other methods adjust ',...
                    'on an epoch by epoch basis - controlling for drift  ',...
                    'or probe adjustment during the recording.'],...
                    'Method:',{'overall','epoch','deppe'},...
                    ['Normalisation by the ''epoch'' or ''deppe'' methods ',...
                    'requires to lower and upper time points of the epoch ',...
                    'period to be defined. These are the time points, ',...
                    'relative to the event marker over which the data is ',...
                    'processed. Word Generation is typically -15 to 25 seconds.'],...
                    'Epoch:','type lower number','type upper number',...
                    ['Normalisation by the ''deppe'' method ',...
                    'requires the lower and upper time points of the epoch and baseline ',...
                    'periods to be defined. These are the time points, ',...
                    'relative to the event marker over which activity is ',...
                    'compared. Generally considered to be a period of non ',...
                    'or control condition behaviour. ',...
                    'Word Generation is typically 5 to 15 seconds.'],...
                    'Baseline:','type lower number','type upper number',...
                    };
                dop.step.next.tag = {'title','info','norm-method_text','norm-method_radio',...
                    'epoch_info','epoch_text','epoch_lower','epoch_upper',...
                    'baseline_info','baseline_text','baseline_lower','baseline_upper'};
                dop.step.next.pos_ht = .1;
                dop.step.next.position = [dop.step.next.title_position;...
                    dop.step.next.info_position;
                    dop.step.next.left_pos .63 .2 dop.step.next.pos_ht; ... % method_text
                    dop.step.next.left_pos+.225 .63 .425 dop.step.next.pos_ht; ... % method_radio
                    dop.step.next.left_pos .475 .7 dop.step.next.pos_ht*1.5; ... % epoch_info
                    dop.step.next.left_pos .4 .2 dop.step.next.pos_ht; ... % epoch_text
                    dop.step.next.left_pos+.225 .4 .2 dop.step.next.pos_ht; ... % epoch_lower
                    dop.step.next.left_pos+.45 .4 .2 dop.step.next.pos_ht; ... % epoch_upper
                    dop.step.next.left_pos .225 .7 dop.step.next.pos_ht*1.5; ... % baseline_info
                    dop.step.next.left_pos .15 .2 dop.step.next.pos_ht; ... % baseline_text
                    dop.step.next.left_pos+.225 .15 .2 dop.step.next.pos_ht; ... % baseline_lower
                    dop.step.next.left_pos+.45 .15 .2 dop.step.next.pos_ht];% ... % baseline_upper
                
                dop.step.next.HorizontalAlignment = [dop.step.next.HorizontalAlignment,...
                    {'center','center',...
                    'left','center','center','center',...
                    'left','center','center','center'}];
                dop.step.next.Enable = {[],[],...
                    'off','off',...
                    [],'off','off','off',...
                    [],'off','off','off'};
                dop.step.next.visible = {'on','on',...
                    'on','on',...
                    'off','off','off','off',...
                    'off','off','off','off'};
                dop.step.next.Callback = {[],[],...
                    [],'dopStepGetDef',...
                    [],[],'dopStepGetDef','dopStepGetDef',...
                    [],[],'dopStepGetDef','dopStepGetDef'};
            case 'epoch'
                dop.step.next.style = {'text','text',...
                    'text','text','edit','edit','edit','text'};
                dop.step.next.string = {'Epoch the data:',...
                    ['''Epoching'' involves dividing the data into ',...
                    'sections surrouding each event marker. You can ',...
                    'think of it like separating out the trials in ',...
                    'a typical experiment - essentially cutting up ',...
                    'a continuous stream of data into pieces. ',...
                    '(please note: if the ''epoch'' button isn''t pushable, ',...
                    'you may have already epoched the data during normalisation).'],...
                    ['In order to do this you need to define the time ',...
                    'period of the epoch. This includes two time points: ',...
                    'the lower time-point of the epoch and the upper. ',...
                    'Where the event marker is set to be time zero, the ',...
                    'lower time-point is usually negative = the time to ',...
                    'include before the event, and the upper is usually ',...
                    'positive = the time to include after the event. ',...
                    'Though this isn''t neccessariliy the case.'],...
                    'Now define the lower and upper time points of your epoch.',...
                    'Epoch:','type lower number','type upper number',...
                    ['After the data are epoched, the ''Plot'' button ',...
                    'will produce epoch plots where the x-axis is ',...
                    'defined by the lower and upper bounds of the epoch. ',...
                    'You can scroll through the plot to look at overall ',...
                    '(ie mean or median summaries) or individual epoch ',...
                    'data.'] ...
                    };
                dop.step.next.tag = {'title','info',...
                    'epoch_info','epoch_info2','epoch_text','epoch_lower','epoch_upper',...
                    'epoch_plot_info'};
                dop.step.next.pos_ht = .1;
                dop.step.next.position = [dop.step.next.title_position;...
                    dop.step.next.info_position;
                    dop.step.next.left_pos .5 .7 .2; ... % epoch_info
                    dop.step.next.left_pos .45 .7 .05; ... % epoch_info 2
                    dop.step.next.left_pos .35 .2 dop.step.next.pos_ht; ... % epoch_text
                    dop.step.next.left_pos+.225 .35 .2 dop.step.next.pos_ht; ... % epoch_lower
                    dop.step.next.left_pos+.45 .35 .2 dop.step.next.pos_ht; ... % epoch_upper
                    dop.step.next.left_pos .15 .7 dop.step.next.pos_ht+.05; ... % epoch_upper
                    ];
                
                dop.step.next.HorizontalAlignment = [dop.step.next.HorizontalAlignment,...
                    {...
                    'left','left','center','center','center','left' ...
                    }];
                dop.step.next.Enable = {[],[],...
                    [],[],'off','on','on','on'};
                dop.step.next.visible = {'on','on',...
                    'off','off','off','on','on','on'};
                dop.step.next.Callback = {[],[],...
                    [],[],[],'dopStepGetDef','dopStepGetDef',[]};
            case 'screen'
                dop.step.next.style = {'text','text',...
                    'text','edit','edit','edit',...
                    'text','edit','edit','edit'};
                dop.step.next.string = {'Epoch Screening:',...
                    ['When averaging a series of trials or epochs, ',...
                    'noise in the data can have a big impact. It''s ',...
                    'therefore common to exclude epochs that include ',...
                    'measurement error. Here we consider two types of noise.'],...
                    ['Participant movement can altered the contact of the ',...
                    'probe leading to extremely low or high velocity values. ',...
                    'Activation screening allows you to specify the lower and ',...
                    'upper limits of acceptable values - epochs with values ',...
                    'outside this range will be excluded.'],...
                    'Activation Range:','type lower number','type upper number',...
                    ['Activation separation refers to the left minus right ',...
                    'difference. We assume that the differences we are ',...
                    'interested in are below 10% change relative to baseline. ',...
                    'This options allows you to exclude epochs with separations ',...
                    'that are likely due to measurement error. You can also specify the ',...
                    'percentage of data that must be affected to exclude the ',...
                    'epoch.'],...
                    'Separation:','type acceptable left minus right difference','type acceptable percentage of affected data',...
                    };
                dop.step.next.tag = {'title','info',...
                    'act_info','act_text','act_lower','act_upper',...
                    'act_sep_info','act_sep_text','act_separation','act_separation_pct'};
                dop.step.next.pos_ht = .1;
                dop.step.next.position = [dop.step.next.title_position;...
                    dop.step.next.info_position;
                    dop.step.next.left_pos .625 .7 dop.step.next.pos_ht*1.5; ... % act_info
                    dop.step.next.left_pos .55 .2 dop.step.next.pos_ht; ... % act_text
                    dop.step.next.left_pos+.225 .55 .2 dop.step.next.pos_ht; ... % act_lower
                    dop.step.next.left_pos+.45 .55 .2 dop.step.next.pos_ht; ... % act_upper
                    dop.step.next.left_pos .35 .7 dop.step.next.pos_ht*1.5; ... % act_sep_info
                    dop.step.next.left_pos .275 .2 dop.step.next.pos_ht; ... % act_sep_text
                    dop.step.next.left_pos+.225 .275 .2 dop.step.next.pos_ht; ... % act_separation
                    dop.step.next.left_pos+.45 .275 .2 dop.step.next.pos_ht];% ... % act_separation_pct
                
                dop.step.next.HorizontalAlignment = [dop.step.next.HorizontalAlignment,...
                    {...
                    'left','center','center','center',...
                    'left','center','center','center'}];
                dop.step.next.Enable = {[],[],...
                    [],'off','on','on',...
                    [],'off','on','on'};
                dop.step.next.visible = {'on','on',...
                    'off','off','off','off',...
                    'off','off','off','off'};
                dop.step.next.Callback = {[],[],...
                    [],[],'dopStepGetDef','dopStepGetDef',...
                    [],[],'dopStepGetDef','dopStepGetDef'};
            case 'baseline'
                dop.step.next.style = {'text','text',...
                    'text','text','edit','edit','edit','text'};
                dop.step.next.string = {'Baseline correction:',...
                    ['Baseline correction involves subtracting the ',...
                    'average activation during a control time period ',...
                    'from all activity within the epoch. This is done ',...
                    'on an epoch by epoch basis.'],...
                    ['The activity during this control period commonly ',...
                    'corresponds to non-activity or non-lateralised ',...
                    'activity.'],...
                    'Now define the lower and upper time points of your baseline period.',...
                    'Baseline:','type lower number','type upper number',...
                    ['After the data are baseline corrected, the activity ',...
                    'during the baseline period will average zero. Activity ',...
                    'outside the baseline period can be considered as ',...
                    'percentage change relative to baseline. Examine the plot ',...
                    'to see this.'] ...
                    };
                dop.step.next.tag = {'title','info',...
                    'baseline_info','baseline_info2','baseline_text','baseline_lower','baseline_upper',...
                    'baseline_plot_info'};
                dop.step.next.pos_ht = .1;
                dop.step.next.position = [dop.step.next.title_position;...
                    dop.step.next.info_position;
                    dop.step.next.left_pos .5 .7 .2; ... % baseline_info
                    dop.step.next.left_pos .45 .7 .05; ... % baseline_info 2
                    dop.step.next.left_pos .35 .2 dop.step.next.pos_ht; ... % baseline_text
                    dop.step.next.left_pos+.225 .35 .2 dop.step.next.pos_ht; ... % baseline_lower
                    dop.step.next.left_pos+.45 .35 .2 dop.step.next.pos_ht; ... % baseline_upper
                    dop.step.next.left_pos .15 .7 dop.step.next.pos_ht+.05; ... % baseline_upper
                    ];
                
                dop.step.next.HorizontalAlignment = [dop.step.next.HorizontalAlignment,...
                    {...
                    'left','left','center','center','center','left' ...
                    }];
                dop.step.next.Enable = {[],[],...
                    [],[],'off','on','on','on'};
                dop.step.next.visible = {'on','on',...
                    'off','off','off','on','on','on'};
                dop.step.next.Callback = {[],[],...
                    [],[],[],'dopStepGetDef','dopStepGetDef',[]};
            case 'li'
                dop.step.next.style = {'text','text',...
                    'text','edit','edit',...
                    'text','edit','edit','edit' ...
                    };
                dop.step.next.string = {'Laterality Index Calculation:',...
                    ['The final part of the processing involves calculating ',...
                    'the ''Laterality Index'' or ''LI''. The is taken as ',...
                    'the average of a time window around the peak left ',...
                    'minus right difference with the period of interest (POI).'],...
                    'The time window is usually 2-seconds.',...
                    'Activation window:','type the duration', ...
                    ['The period of interest (POI) follows the onset of ',...
                    'a stimuation period by about 5-seconds due to the ',...
                    'delay of neuro-metabolic coupling.'],...
                    'POI:','type lower number','type upper number' ...
                    };
                dop.step.next.tag = {'title','info',...
                    'act_window_info','act_window_text','act_window',...
                    'poi_info','poi_text','poi_lower','poi_upper' ...
                    };
                dop.step.next.pos_ht = .1;
                dop.step.next.position = [dop.step.next.title_position;...
                    dop.step.next.info_position;
                    dop.step.next.left_pos .55 .7 dop.step.next.pos_ht*1.5; ... % act_window_info
                    dop.step.next.left_pos .55 .2 dop.step.next.pos_ht; ... % act_window_text
                    dop.step.next.left_pos+.225 .55 .2 dop.step.next.pos_ht; ... % act_window
                    dop.step.next.left_pos .35 .7 dop.step.next.pos_ht*1.5; ... % poi_info
                    dop.step.next.left_pos .275 .2 dop.step.next.pos_ht; ... % poi_text
                    dop.step.next.left_pos+.225 .275 .2 dop.step.next.pos_ht; ... % poi_lower
                    dop.step.next.left_pos+.45 .275 .2 dop.step.next.pos_ht; ... % poi_upper
                    ];
                
                dop.step.next.HorizontalAlignment = [dop.step.next.HorizontalAlignment,...
                    {...
                    'left','center','center',...
                    'left','center','center','center' ...
                    }];
                dop.step.next.Enable = {[],[],...
                    [],'off','on',...
                    [],'off','on','on' ...
                    };
                dop.step.next.visible = {'on','on',...
                    'off','off','off',...
                    'off','off','off','off' ...
                    };
                dop.step.next.Callback = {[],[],...
                    [],[],'dopStepGetDef',...
                    [],[],'dopStepGetDef','dopStepGetDef' ...
                    };
            case 'timing'
                dop.step.next.size = [.2 .05];
                dop.step.next.options = {'epoch','base','poi'};
                dop.step.next.colours = {[.9 .9 0],[0 0 0],[.2 .7 .1]};%{'y','k','g'};
                dop.step.next.style = {'text','text','text','text',...
                    'edit','edit','edit','text',...
                    'edit','edit','edit','text',...
                    'edit','edit','edit','text',...
                    'axes'};
                dop.step.next.string = {'Period timing:',...
                    ['Now we''ll define some of the timing for the processing. ',...
                    'Epoch = limits of the data around the event marker. ',...
                    'Baseline = limits of the data to be used for baseline correction. ',...
                    'Period of interest = limits within which the laterality index is calculated. '],...
                    'Lower','Upper',...
                    'Epoch','type a number','type a number',[],...
                    'Baseline','type a number','type a number',[],...
                    'Period of Interest','type a number','type a number',[],...
                    []};
                
                dop.step.next.tag = {'title','info','lower_text','upper_text',...
                    'epoch_text','epoch_lower','epoch_upper','epoch_col',...
                    'baseline_text','baseline_lower','baseline_upper','baseline_col',...
                    'poi_text','poi_lower','poi_upper','poi_col',...
                    'timing_plot'};
                dop.step.next.col = cell(1,numel(dop.step.next.tag));
                dop.step.next.lims = {'lower','upper'};
                for i = 1 : numel(dop.step.next.options)
                    dop.tmp.tag = sprintf('%s_col',dop.step.next.options{i});
                    dop.step.next.col{ismember(dop.step.next.tag,dop.tmp.tag)} = dop.step.next.colours{i};
                    for j = 1 : numel(dop.step.next.lims)
                        if isfield(dop,'def') && isfield(dop.def,dop.step.next.options{i})
                            dop.tmp.tag = sprintf('%s_%s',dop.step.next.options{i},dop.step.next.lims{j});
                            dop.step.next.string{ismember(dop.step.next.tag,dop.tmp.tag)} = ...
                                num2str(dop.def.(dop.step.next.options{i})(j));
                        end
                    end
                end
                dop.step.next.position = [dop.step.next.title_position;...
                    dop.step.next.info_position;
                    .35 .6 .2 .1; .6 .6 .2 .1;...
                    .1 .6 dop.step.next.size; .35 .6 dop.step.next.size; .6 .6 dop.step.next.size; .85 .6 .05 .05;...
                    .1 .525 dop.step.next.size; .35 .525 dop.step.next.size; .6 .525 dop.step.next.size; .85 .525 .05 .05;...
                    .1 .45 dop.step.next.size; .35 .45 dop.step.next.size; .6 .45 dop.step.next.size; .85 .45 .05 .05;...
                    .1 .3 .8 .125];
                dop.step.next.HorizontalAlignment = [dop.step.next.HorizontalAlignment,{'center','center',...
                    'center','center','center','left',...
                    'center','center','center','left',...
                    'center','center','center','left',[]}];
                dop.step.next.Enable = {[],[],[],[],'off','on','on','on'...
                    'off','on','on','on','off','on','on','on',[]};
                dop.step.next.Callback = {[],[],[],[],...
                    [],'dopStepGetDef','dopStepGetDef',[],...
                    [],'dopStepGetDef','dopStepGetDef',[],...
                    [],'dopStepGetDef','dopStepGetDef',[],[]};
            case 'save_info'
                dop.step.next.style = {'text','text',...
                    'edit','edit','pushbutton',...
                    'text','text','text',...
                    };
                dop.step.next.string = {'Save summary statistics:',...
                    ['This allows you to save various statistics to a data file. ',...
                    'Due to space, the explanatory information is included  ',...
                    'in ''rollover'' help so hover the mouse over components ',...
                    'for further information.'],...
                    'Directory:','type base directory','Browse',...
                    };
                dop.step.next.tag = {'title','info','save_dir_text','save_dir_edit','save_dir_browse',...
                    };
                dop.step.next.tooltip = {'','','',... 
                    'Type in save directory (much better to browse for it though...)'... % edit
                   'Click to browse for save directory',... % browse
                    '','',''};
                dop.step.next.position = [dop.step.next.title_position;... [dop.step.next.left_pos .87 .7 .1];
                    dop.step.next.info_position;... [dop.step.next.left_pos .7 .7 .1];
                    dop.step.next.left_pos .65 .1 .1; ... % text
                    dop.step.next.left_pos+.1 .65 .5 .1;... % edit
                    dop.step.next.left_pos+.1+.5 .65 .1 .1; % browse
                    dop.step.next.left_pos .55 .1 .1; ... % text {'Summary','overall','epoch'},...
                    ];
                dop.step.next.HorizontalAlignment = ...
                    [dop.step.next.HorizontalAlignment,...
                    {'center','center','center'},...
                    {'center','left','left'},...
                    {'center','left','left','left','left'},...
                    {'center','left','left','left'},...
                    {'center','left','left','left','left'},...
                    {'center','left','left','left','left'},...
                    ];
                dop.step.next.Enable = [{[],[],'off','on','on'},...
                    {'on','on','on'}
                    ];
                dop.step.next.visible = ...
                    repmat({'on'},1,numel(dop.step.next.tag));
                dop.step.next.Callback = {[],[],[],[],[],[],[],[]};
            case 'save'
                dop.step.next.style = {'text','text',...
                    'edit','edit','pushbutton',...
                    'edit','checkbox','checkbox',... % summary
                    'edit','checkbox','checkbox','checkbox','checkbox',... % channels
                    'edit','checkbox','checkbox','checkbox',... % periods
                    'edit','checkbox','checkbox','checkbox','checkbox',... % epochs
                    'edit','checkbox','checkbox','checkbox','checkbox', ... % variables
                    };
                dop.step.next.string = {'Save summary statistics:',...
                    ['This allows you to save various statistics to a data file. ',...
                    'Due to space, the explanatory information is included  ',...
                    'in ''rollover'' help so hover the mouse over components ',...
                    'for further information.'],...
                    'Directory:','type base directory','Browse',...
                    'Summary','overall','epoch',...{'Summary','overall','epoch'},...
                    'Channels','Left','Right','Difference','Average',...{'Channels','Left','Right','Difference','Average'},...
                    'Periods','epoch','baseline','poi',... {'Periods','epoch','base','poi'},... 
                    'Epochs','all','screen','odd','even',...{'Epochs','all','screen','odd','even'},...
                    'Variables','n','LI','SD','Latency'}; %{'Variables','n','LI','SD','Latency'}}; % 
                dop.step.next.tag = {'title','info','save_dir_text','save_dir_edit','save_dir_browse',...
                    'summary_text','save_summary_overall','save_summary_epoch'...
                    'channels_text','save_channels_left','save_channels_right','save_channels_difference','save_channels_average',...
                    'periods_text','save_periods_epoch','save_periods_baseline','save_periods_poi',...
                    'epochs_text','save_epochs_all','save_epochs_screen','save_epochs_odd','save_epochs_even'...
                    'variables_text','save_variables_n','save_variables_LI','save_variables_SD','save_variables_Latency'};
                dop.step.next.tooltip = {'','','',... 
                    'Type in save directory (much better to browse for it though...)'... % edit
                   'Click to browse for save directory',... % browse
                    '', ... % text {'Summary','overall','epoch'},...
                    'Check to save summaries for a set of epochs', ... % checkbox
                    'Check to save summaries for each individual epoch' ... % checkbox
                    '', ... % text {'Channels','Left','Right','Difference','Average'}
                    'Check to save summaries for the left channel', ... % check
                    'Check to save summaries for the right channel', ... % check
                    'Check to save summaries for the left minus right different', ... % check
                    'Check to save summaries for the average of the left and right channels', ... % check
                    '', ... % text {'Periods','epoch','base','poi'}
                    'Check to save summaries related to the whole epoch', ... % check
                    'Check to save summaries related to the baseline period', ... % check
                    'Check to save summaries related to the period of interest (poi)', ... % check
                    '', ...% text {'Epochs','all','screen','odd','even'}
                    'Check to save summaries derived from all available epochs (ie no epoch screening)', ... % check
                    'Check to save summaries derived from only screened epochs', ... % check
                    'Check to save summaries derived from odd numbered epoches (after screening - for split-half reliability calculations)', ... % check
                    'Check to save summaries derived from even numbered epoches (after screening - for split-half reliability calculations)', ... % check
                    '', ... % text {'Variables','n','LI','SD','Latency'}
                    'Check to save the number of epochs used in the summary', ... % check
                    'Check to save the Laterality Index (ie mean activity around the peak in the selection period/s)', ... % check
                    'Check to save the standard deviation of the mean values at the peak for each epoch', ... % check
                    'Check to save the latency/timing of the peak (in seconds)', ... % check
                    };
                dop.step.next.position = [dop.step.next.title_position;... [dop.step.next.left_pos .87 .7 .1];
                    dop.step.next.info_position;... [dop.step.next.left_pos .7 .7 .1];
                    dop.step.next.left_pos .65 .1 .1; ... % text
                    dop.step.next.left_pos+.1 .65 .5 .1;... % edit
                    dop.step.next.left_pos+.1+.5 .65 .1 .1; % browse
                    dop.step.next.left_pos .55 .1 .1; ... % text {'Summary','overall','epoch'},...
                    dop.step.next.left_pos+.1 .55 .1 .1; ... % checkbox
                    dop.step.next.left_pos+.2 .55 .1 .1; ... % checkbox
                    dop.step.next.left_pos .45 .1 .1; ... % text {'Channels','Left','Right','Difference','Average'}
                    dop.step.next.left_pos+.1 .45 .1 .1; ... % check
                    dop.step.next.left_pos+.2 .45 .1 .1; ... % check
                    dop.step.next.left_pos+.3 .45 .1 .1; ... % check
                    dop.step.next.left_pos+.4 .45 .1 .1; ... % check
                    dop.step.next.left_pos .35 .1 .1; ... % text {'Periods','epoch','base','poi'}
                    dop.step.next.left_pos+.1 .35 .1 .1; ... % check
                    dop.step.next.left_pos+.2 .35 .1 .1; ... % check
                    dop.step.next.left_pos+.3 .35 .1 .1; ... % check
                    dop.step.next.left_pos .25 .1 .1; ... % text {'Epochs','all','screen','odd','even'}
                    dop.step.next.left_pos+.1 .25 .1 .1; ... % check
                    dop.step.next.left_pos+.2 .25 .1 .1; ... % check
                    dop.step.next.left_pos+.3 .25 .1 .1; ... % check
                    dop.step.next.left_pos+.4 .25 .1 .1; ... % check
                    dop.step.next.left_pos .15 .1 .1; ... % text {'Variables','n','LI','SD','Latency'}
                    dop.step.next.left_pos+.1 .15 .1 .1; ... % check
                    dop.step.next.left_pos+.2 .15 .1 .1; ... % check
                    dop.step.next.left_pos+.3 .15 .1 .1; ... % check
                    dop.step.next.left_pos+.4 .15 .1 .1; ... % check
                    ]; %title2
                dop.step.next.HorizontalAlignment = ...
                    [dop.step.next.HorizontalAlignment,...
                    {'center','center','center'},...
                    {'center','left','left'},...
                    {'center','left','left','left','left'},...
                    {'center','left','left','left'},...
                    {'center','left','left','left','left'},...
                    {'center','left','left','left','left'},...
                    ];
                dop.step.next.Enable = [{[],[],'off','on','on'},...
                    {'off','on','on'},...
                    {'off','on','on','on','on'},...
                    {'off','on','on','on'},...
                    {'off','on','on','on','on'},...
                    {'off','on','on','on','on'},...
                    ];
                dop.step.next.checked = [0,0,0,0,0,...
                    0,1,0,...'off','on','on'},... summary
                    0,0,0,1,0,...{'off','on','on','on','on'},... chs
                    0,0,0,1,...{'off','on','on','on'},... epochs
                    0,0,1,0,0,...{'off','on','on','on','on'},... periods 
                    0,1,1,1,1,...{'off','on','on','on','on'},... variables
                    ];
                dop.step.next.visible = ...
                    repmat({'on'},1,numel(dop.step.next.tag));
                dop.step.next.Callback = [{[],[],[],[],[]},...
                    repmat({'dopStepGetDef'},1,numel(dop.step.next.tag)-5)];
            case 'task_name'
                dop.step.next.style = {'text','edit','edit'};
                dop.step.next.string = {...
                    ['Let''s give the task a name. This will ', ...
                    'be used for labelling folders and variables. Please ', ...
                    'make sure it doesn''t have any spaces.'],...
                    'Task Name:','dopplerTask'};
                dop.step.next.tag = {'info','task_name_text','task_name'};
                dop.step.next.position = [dop.step.next.info_position;
                    .3 .5 .2 .1; .5 .5 .2 .1];
                dop.step.next.HorizontalAlignment = [dop.step.next.HorizontalAlignment,{'center'}];
                dop.step.next.Enable = {[],'off','on'};
                dop.step.next.Callback = {[],[],'dopStepGetDef'};
            case 'definition'
                dop.step.next.style = {'text'};
                dop.step.next.string = {...
                    ['Let''s start by definining a few parameters for ',...
                    'your data']};
                dop.step.next.tag = {'info'};
                dop.step.next.position = dop.step.next.info_position;
            otherwise
                dop.step.next.style = {'text'};
                dop.step.next.string = {...
                    sprintf('I''m afraid ''%s'' hasn''t been programmed yet',dop.step.next.name)};
                dop.step.next.tag = {'info'};
                dop.step.next.position = dop.step.next.info_position;

        end
    end
    dopStepUpdate(dop);
catch err
    save(dopOSCCIdebug);rethrow(err);
end
end